### PR TITLE
Fix undo-cd bug

### LINKED ISSUE #191: Having 2 decks, cd 1 then undo will delete all cards inside that deck

### PR DESCRIPTION
**Pull request by Lessthanfree**
Implement flag to block undo operation for cd commands.
Resolves #191

Also introduced `Deck` currentDeck and `boolean` justEnteredDeck` to Anakin

Also fixed exception handling for import

Added Personal project portfolio

### CODE REVIEW

File: src/main/java/seedu/address/model/Anakin.java [hunk 1]
```diff
@@ -141,8 +165,10 @@ public void getOutOfDeck() {
             throw new IllegalOperationWhileReviewingDeckException();
         }
         isInsideDeck = false;
-        cards = new UniqueCardList();
+        currentDeck = NULLDECK;
+        clearCards();
         updateDisplayedCards();
+        jedfalse();
```
Comment (leeyjjoel) [inline src/main/java/seedu/address/model/Anakin.java]: /nitpick can we get an alternative name for jedfalse? Took me some time to figure out what it referred to

Comment (Lessthanfree) [reply src/main/java/seedu/address/model/Anakin.java]: oh yep I was intending to refactor that

File: src/main/java/seedu/address/logic/commands/UndoCommand.java [hunk 2]
```diff
@@ -25,6 +26,10 @@ public CommandResult execute(Model model, CommandHistory history) throws Command
             throw new CommandException(MESSAGE_CURRENTLY_REVIEWING_DECK);
         }
 
+        if(model.justEnteredDeck()) {
```
[the remark this answers is not in the document]
Comment (Lessthanfree) [reply src/main/java/seedu/address/logic/commands/UndoCommand.java]: Yes, the chain of undo is broken by the fact that undo cannot be performed on the cd command
